<?php


namespace app\models;

use yii\base\Model;

class ActivityCalendar extends Model
{

    public $date;
    $date=date("d/m/Y");

    public function rules()
    {
        ['date','string']
        return parent::rules(); // TODO: Change the autogenerated stub
    }


}